// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_NATIVEPARCELABLEMAP_HPP_JNI_
#define DJINNI_GENERATED_NATIVEPARCELABLEMAP_HPP_JNI_

#include "djinni_support.hpp"
#include "parcelable_map.hpp"

namespace djinni_generated {

class NativeParcelableMap final {
public:
    using CppType = ::testsuite::ParcelableMap;
    using JniType = jobject;

    using Boxed = NativeParcelableMap;

    ~NativeParcelableMap();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeParcelableMap();
    friend ::djinni::JniClass<NativeParcelableMap>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ParcelableMap") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/HashMap;)V") };
    const jfieldID field_mM { ::djinni::jniGetFieldID(clazz.get(), "mM", "Ljava/util/HashMap;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVEPARCELABLEMAP_HPP_JNI_
