// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from primitive_list.djinni

#ifndef DJINNI_GENERATED_NATIVEPRIMITIVELIST_HPP_JNI_
#define DJINNI_GENERATED_NATIVEPRIMITIVELIST_HPP_JNI_

#include "djinni_support.hpp"
#include "primitive_list.hpp"

namespace djinni_generated {

class NativePrimitiveList final {
public:
    using CppType = ::testsuite::PrimitiveList;
    using JniType = jobject;

    using Boxed = NativePrimitiveList;

    ~NativePrimitiveList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativePrimitiveList();
    friend ::djinni::JniClass<NativePrimitiveList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/PrimitiveList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mList { ::djinni::jniGetFieldID(clazz.get(), "mList", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVEPRIMITIVELIST_HPP_JNI_
