// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#ifndef DJINNI_GENERATED_NATIVECONSTANTS_HPP_JNI_
#define DJINNI_GENERATED_NATIVECONSTANTS_HPP_JNI_

#include "constants.hpp"
#include "djinni_support.hpp"

namespace djinni_generated {

class NativeConstants final {
public:
    using CppType = ::testsuite::Constants;
    using JniType = jobject;

    using Boxed = NativeConstants;

    ~NativeConstants();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeConstants();
    friend ::djinni::JniClass<NativeConstants>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/Constants") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "()V") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVECONSTANTS_HPP_JNI_
