// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_NATIVEPARCELABLEOPTIONALMAP_HPP_JNI_
#define DJINNI_GENERATED_NATIVEPARCELABLEOPTIONALMAP_HPP_JNI_

#include "djinni_support.hpp"
#include "parcelable_optional_map.hpp"

namespace djinni_generated {

class NativeParcelableOptionalMap final {
public:
    using CppType = ::testsuite::ParcelableOptionalMap;
    using JniType = jobject;

    using Boxed = NativeParcelableOptionalMap;

    ~NativeParcelableOptionalMap();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeParcelableOptionalMap();
    friend ::djinni::JniClass<NativeParcelableOptionalMap>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ParcelableOptionalMap") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/HashMap;)V") };
    const jfieldID field_mOptionalSet { ::djinni::jniGetFieldID(clazz.get(), "mOptionalSet", "Ljava/util/HashMap;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVEPARCELABLEOPTIONALMAP_HPP_JNI_
