// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_NATIVEPARCELABLELIST_HPP_JNI_
#define DJINNI_GENERATED_NATIVEPARCELABLELIST_HPP_JNI_

#include "djinni_support.hpp"
#include "parcelable_list.hpp"

namespace djinni_generated {

class NativeParcelableList final {
public:
    using CppType = ::testsuite::ParcelableList;
    using JniType = jobject;

    using Boxed = NativeParcelableList;

    ~NativeParcelableList();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeParcelableList();
    friend ::djinni::JniClass<NativeParcelableList>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ParcelableList") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mL { ::djinni::jniGetFieldID(clazz.get(), "mL", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVEPARCELABLELIST_HPP_JNI_
