// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_NATIVEPARCELABLELISTMAPSET_HPP_JNI_
#define DJINNI_GENERATED_NATIVEPARCELABLELISTMAPSET_HPP_JNI_

#include "djinni_support.hpp"
#include "parcelable_list_map_set.hpp"

namespace djinni_generated {

class NativeParcelableListMapSet final {
public:
    using CppType = ::testsuite::ParcelableListMapSet;
    using JniType = jobject;

    using Boxed = NativeParcelableListMapSet;

    ~NativeParcelableListMapSet();

    static CppType toCpp(JNIEnv* jniEnv, JniType j);
    static ::djinni::LocalRef<JniType> fromCpp(JNIEnv* jniEnv, const CppType& c);

private:
    NativeParcelableListMapSet();
    friend ::djinni::JniClass<NativeParcelableListMapSet>;

    const ::djinni::GlobalRef<jclass> clazz { ::djinni::jniFindClass("com/dropbox/djinni/test/ParcelableListMapSet") };
    const jmethodID jconstructor { ::djinni::jniGetMethodID(clazz.get(), "<init>", "(Ljava/util/ArrayList;)V") };
    const jfieldID field_mListMapSet { ::djinni::jniGetFieldID(clazz.get(), "mListMapSet", "Ljava/util/ArrayList;") };
};

}  // namespace djinni_generated
#endif //DJINNI_GENERATED_NATIVEPARCELABLELISTMAPSET_HPP_JNI_
