// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#ifndef DJINNI_GENERATED__VARNAME_INTERFACE__HPP
#define DJINNI_GENERATED__VARNAME_INTERFACE__HPP

#include <memory>

namespace testsuite {

struct VarnameRecord;

class VarnameInterface {
public:
    virtual ~VarnameInterface() {}

    /**
     * We should also rewrite parameter names in docstrings.
     * _r_arg_ should be rewritten.
     * _i_arg_ should not.
     */
    virtual VarnameRecord _rmethod_(const VarnameRecord & _r_arg_) = 0;

    virtual std::shared_ptr<VarnameInterface> _imethod_(const std::shared_ptr<VarnameInterface> & _i_arg_) = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED__VARNAME_INTERFACE__HPP
