// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from varnames.djinni

#ifndef DJINNI_GENERATED__VARNAME_RECORD__HPP
#define DJINNI_GENERATED__VARNAME_RECORD__HPP

#include <cstdint>
#include <iostream>
#include <utility>

namespace testsuite {

/**
 * Underscore is used as a separator in Djinni names, so we don't really
 * anticipate it to be used as a prefix/suffix.  Some name styles behave
 * badly when it is.  However this test case ensures we at least don't crash.
 */
struct VarnameRecord final {
    int8_t _field_;

    VarnameRecord(int8_t _field__)
    : _field_(std::move(_field__))
    {}

    VarnameRecord(const VarnameRecord& cpy) {
       this->_field_ = cpy._field_;
    }

    VarnameRecord() = default;


    VarnameRecord& operator=(const VarnameRecord& cpy) {
       this->_field_ = cpy._field_;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(_field_);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(_field_);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED__VARNAME_RECORD__HPP
