// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum.djinni

#ifndef DJINNI_GENERATED_COLOR_HPP
#define DJINNI_GENERATED_COLOR_HPP

#include <functional>
#include <iostream>
#include <string>

namespace testsuite {

enum class color : int {
    RED,
    ORANGE,
    YELLOW,
    GREEN,
    BLUE,
    /**
     * "It is customary to list indigo as a color lying between blue and violet, but it has
     * never seemed to me that indigo is worth the dignity of being considered a separate
     * color. To my eyes it seems merely deep blue." --Isaac Asimov
     */
    INDIGO,
    VIOLET,
};
 std::string to_string(const color& color);
 std::ostream &operator<<(std::ostream &os, const color &o);

}  // namespace testsuite

namespace std {

template <>
struct hash<::testsuite::color> {
    size_t operator()(::testsuite::color type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
#endif //DJINNI_GENERATED_COLOR_HPP
