// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#ifndef DJINNI_GENERATED_CONFLICT_HPP
#define DJINNI_GENERATED_CONFLICT_HPP

namespace testsuite {

/**
 * Test for conflict of method name with an interface name.
 * See the comments about scopeSymbols in CppMarshal.scala for more info.
 */
class Conflict {
public:
    virtual ~Conflict() {}
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CONFLICT_HPP
