// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#ifndef DJINNI_GENERATED_CONFLICT_USER_HPP
#define DJINNI_GENERATED_CONFLICT_USER_HPP

#include <memory>
#include <unordered_set>

namespace testsuite {

class Conflict;

class ConflictUser {
public:
    virtual ~ConflictUser() {}

    virtual std::shared_ptr<::testsuite::Conflict> Conflict() = 0;

    virtual bool conflict_arg(const std::unordered_set<std::shared_ptr<::testsuite::Conflict>> & cs) = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CONFLICT_USER_HPP
