// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#ifndef DJINNI_GENERATED_CONSTANT_INTERFACE_WITH_ENUM_HPP
#define DJINNI_GENERATED_CONSTANT_INTERFACE_WITH_ENUM_HPP

namespace testsuite {

enum class constant_enum;

/** Interface containing enum constant */
class ConstantInterfaceWithEnum {
public:
    virtual ~ConstantInterfaceWithEnum() {}

    static constant_enum const CONST_ENUM;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CONSTANT_INTERFACE_WITH_ENUM_HPP
