// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#ifndef DJINNI_GENERATED_CONSTANT_WITH_ENUM_HPP
#define DJINNI_GENERATED_CONSTANT_WITH_ENUM_HPP

#include "constant_enum.hpp"
#include <iostream>
#include <utility>

namespace testsuite {

/** Record containing enum constant */
struct ConstantWithEnum final {

    static constant_enum const CONST_ENUM;

    template <class Archive>
    void load(Archive& archive) {
        archive();
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive();
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CONSTANT_WITH_ENUM_HPP
