// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constants.djinni

#ifndef DJINNI_GENERATED_CONSTANT_RECORD_HPP
#define DJINNI_GENERATED_CONSTANT_RECORD_HPP

#include <cstdint>
#include <iostream>
#include <string>
#include <utility>

namespace testsuite {

/** Record for use in constants */
struct ConstantRecord final {
    int32_t some_integer;
    std::string some_string;

    ConstantRecord(int32_t some_integer_,
                   std::string some_string_)
    : some_integer(std::move(some_integer_))
    , some_string(std::move(some_string_))
    {}

    ConstantRecord(const ConstantRecord& cpy) {
       this->some_integer = cpy.some_integer;
       this->some_string = cpy.some_string;
    }

    ConstantRecord() = default;


    ConstantRecord& operator=(const ConstantRecord& cpy) {
       this->some_integer = cpy.some_integer;
       this->some_string = cpy.some_string;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(some_integer, some_string);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(some_integer, some_string);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CONSTANT_RECORD_HPP
