// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#ifndef DJINNI_GENERATED_CONSTANT_ENUM_HPP
#define DJINNI_GENERATED_CONSTANT_ENUM_HPP

#include <functional>
#include <iostream>
#include <string>

namespace testsuite {

enum class constant_enum : int {
    SOME_VALUE,
    SOME_OTHER_VALUE,
};
 std::string to_string(const constant_enum& constant_enum);
 std::ostream &operator<<(std::ostream &os, const constant_enum &o);

}  // namespace testsuite

namespace std {

template <>
struct hash<::testsuite::constant_enum> {
    size_t operator()(::testsuite::constant_enum type) const {
        return std::hash<int>()(static_cast<int>(type));
    }
};

}  // namespace std
#endif //DJINNI_GENERATED_CONSTANT_ENUM_HPP
