// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from exception.djinni

#ifndef DJINNI_GENERATED_CPP_EXCEPTION_HPP
#define DJINNI_GENERATED_CPP_EXCEPTION_HPP

#include <cstdint>
#include <memory>

namespace testsuite {

class CppException {
public:
    virtual ~CppException() {}

    virtual int32_t throw_an_exception() = 0;

    static std::shared_ptr<CppException> get();
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_CPP_EXCEPTION_HPP
