// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#ifndef DJINNI_GENERATED_DATE_RECORD_HPP
#define DJINNI_GENERATED_DATE_RECORD_HPP

#include <chrono>
#include <iostream>
#include <utility>

namespace testsuite {

struct DateRecord final {
    std::chrono::system_clock::time_point created_at;

    friend bool operator==(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator!=(const DateRecord& lhs, const DateRecord& rhs);

    friend bool operator<(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator>(const DateRecord& lhs, const DateRecord& rhs);

    friend bool operator<=(const DateRecord& lhs, const DateRecord& rhs);
    friend bool operator>=(const DateRecord& lhs, const DateRecord& rhs);

    DateRecord(std::chrono::system_clock::time_point created_at_)
    : created_at(std::move(created_at_))
    {}

    DateRecord(const DateRecord& cpy) {
       this->created_at = cpy.created_at;
    }

    DateRecord() = default;


    DateRecord& operator=(const DateRecord& cpy) {
       this->created_at = cpy.created_at;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(created_at);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(created_at);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_DATE_RECORD_HPP
