// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#ifndef DJINNI_GENERATED_EMPTY_RECORD_HPP
#define DJINNI_GENERATED_EMPTY_RECORD_HPP

#include <iostream>
#include <utility>

namespace testsuite {

/**
 * Empty record
 * (Second line of multi-line documentation.
 *   Indented third line of multi-line documentation.)
 */
struct EmptyRecord final {

    template <class Archive>
    void load(Archive& archive) {
        archive();
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive();
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_EMPTY_RECORD_HPP
