// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from constant_enum.djinni

#ifndef DJINNI_GENERATED_ENUM_FROM_STRING_HPP
#define DJINNI_GENERATED_ENUM_FROM_STRING_HPP

#include <string>

namespace testsuite {

template <typename T> 
T from_string(const std::string&);

}  // namespace testsuite
#endif //DJINNI_GENERATED_ENUM_FROM_STRING_HPP
