// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#ifndef DJINNI_GENERATED_EXTENDED_RECORD_BASE_HPP
#define DJINNI_GENERATED_EXTENDED_RECORD_BASE_HPP

#include <iostream>
#include <utility>

namespace testsuite {

struct ExtendedRecord; // Requiring extended class

/** Extended record */
struct ExtendedRecordBase {

    static ExtendedRecord const EXTENDED_RECORD_CONST;
    bool foo;

    ExtendedRecordBase(bool foo_)
    : foo(std::move(foo_))
    {}

    ExtendedRecordBase(const ExtendedRecordBase& cpy) {
       this->foo = cpy.foo;
    }

    ExtendedRecordBase() = default;


    ExtendedRecordBase& operator=(const ExtendedRecordBase& cpy) {
       this->foo = cpy.foo;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(foo);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(foo);
    }

    virtual ~ExtendedRecordBase() = default;

protected:
    ExtendedRecordBase(const ExtendedRecordBase&) = default;
    ExtendedRecordBase(ExtendedRecordBase&&) = default;
    ExtendedRecordBase& operator=(const ExtendedRecordBase&) = default;
    ExtendedRecordBase& operator=(ExtendedRecordBase&&) = default;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_EXTENDED_RECORD_BASE_HPP
