// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#ifndef DJINNI_GENERATED_EXTERN_INTERFACE_2_HPP
#define DJINNI_GENERATED_EXTERN_INTERFACE_2_HPP

#include "test_helpers.hpp"
#include <memory>

struct ExternRecordWithDerivings;

class ExternInterface2 {
public:
    virtual ~ExternInterface2() {}

    virtual ExternRecordWithDerivings foo(const std::shared_ptr<::testsuite::TestHelpers> & i) = 0;
};
#endif //DJINNI_GENERATED_EXTERN_INTERFACE_2_HPP
