// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#ifndef DJINNI_GENERATED_FIRST_LISTENER_HPP
#define DJINNI_GENERATED_FIRST_LISTENER_HPP

namespace testsuite {

/** Used for ObjC multiple inheritance tests */
class FirstListener {
public:
    virtual ~FirstListener() {}

    virtual void first() = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_FIRST_LISTENER_HPP
