// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from extended_record.djinni

#ifndef DJINNI_GENERATED_INTERFACE_USING_EXTENDED_RECORD_HPP
#define DJINNI_GENERATED_INTERFACE_USING_EXTENDED_RECORD_HPP

namespace testsuite {

struct ExtendedRecord;
struct RecordUsingExtendedRecord;

class InterfaceUsingExtendedRecord {
public:
    virtual ~InterfaceUsingExtendedRecord() {}

    static RecordUsingExtendedRecord const CR;

    virtual ExtendedRecord meth(const ExtendedRecord & er) = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_INTERFACE_USING_EXTENDED_RECORD_HPP
