// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#ifndef DJINNI_GENERATED_JAVA_ONLY_LISTENER_HPP
#define DJINNI_GENERATED_JAVA_ONLY_LISTENER_HPP

namespace testsuite {

class JavaOnlyListener {
public:
    virtual ~JavaOnlyListener() {}
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_JAVA_ONLY_LISTENER_HPP
