// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from map.djinni

#ifndef DJINNI_GENERATED_MAP_LIST_RECORD_HPP
#define DJINNI_GENERATED_MAP_LIST_RECORD_HPP

#include <cstdint>
#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace testsuite {

struct MapListRecord final {
    std::vector<std::unordered_map<std::string, int64_t>> map_list;

    MapListRecord(std::vector<std::unordered_map<std::string, int64_t>> map_list_)
    : map_list(std::move(map_list_))
    {}

    MapListRecord(const MapListRecord& cpy) {
       this->map_list = cpy.map_list;
    }

    MapListRecord() = default;


    MapListRecord& operator=(const MapListRecord& cpy) {
       this->map_list = cpy.map_list;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(map_list);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(map_list);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_MAP_LIST_RECORD_HPP
