// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from date.djinni

#ifndef DJINNI_GENERATED_MAP_DATE_RECORD_HPP
#define DJINNI_GENERATED_MAP_DATE_RECORD_HPP

#include <chrono>
#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>

namespace testsuite {

struct MapDateRecord final {
    std::unordered_map<std::string, std::chrono::system_clock::time_point> dates_by_id;

    MapDateRecord(std::unordered_map<std::string, std::chrono::system_clock::time_point> dates_by_id_)
    : dates_by_id(std::move(dates_by_id_))
    {}

    MapDateRecord(const MapDateRecord& cpy) {
       this->dates_by_id = cpy.dates_by_id;
    }

    MapDateRecord() = default;


    MapDateRecord& operator=(const MapDateRecord& cpy) {
       this->dates_by_id = cpy.dates_by_id;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(dates_by_id);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(dates_by_id);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_MAP_DATE_RECORD_HPP
