// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from nested_collection.djinni

#ifndef DJINNI_GENERATED_NESTED_COLLECTION_HPP
#define DJINNI_GENERATED_NESTED_COLLECTION_HPP

#include <iostream>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace testsuite {

struct NestedCollection final {
    std::vector<std::unordered_set<std::string>> set_list;

    NestedCollection(std::vector<std::unordered_set<std::string>> set_list_)
    : set_list(std::move(set_list_))
    {}

    NestedCollection(const NestedCollection& cpy) {
       this->set_list = cpy.set_list;
    }

    NestedCollection() = default;


    NestedCollection& operator=(const NestedCollection& cpy) {
       this->set_list = cpy.set_list;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(set_list);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(set_list);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_NESTED_COLLECTION_HPP
