// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_LIST_MAP_SET_HPP
#define DJINNI_GENERATED_PARCELABLE_LIST_MAP_SET_HPP

#include <iostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableListMapSet final {
    std::vector<std::unordered_map<std::string, std::unordered_set<std::string>>> list_map_set;

    ParcelableListMapSet(std::vector<std::unordered_map<std::string, std::unordered_set<std::string>>> list_map_set_)
    : list_map_set(std::move(list_map_set_))
    {}

    ParcelableListMapSet(const ParcelableListMapSet& cpy) {
       this->list_map_set = cpy.list_map_set;
    }

    ParcelableListMapSet() = default;


    ParcelableListMapSet& operator=(const ParcelableListMapSet& cpy) {
       this->list_map_set = cpy.list_map_set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(list_map_set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(list_map_set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_LIST_MAP_SET_HPP
