// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_LIST_SET_HPP
#define DJINNI_GENERATED_PARCELABLE_LIST_SET_HPP

#include <iostream>
#include <string>
#include <unordered_set>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableListSet final {
    std::vector<std::unordered_set<std::string>> list_set;

    ParcelableListSet(std::vector<std::unordered_set<std::string>> list_set_)
    : list_set(std::move(list_set_))
    {}

    ParcelableListSet(const ParcelableListSet& cpy) {
       this->list_set = cpy.list_set;
    }

    ParcelableListSet() = default;


    ParcelableListSet& operator=(const ParcelableListSet& cpy) {
       this->list_set = cpy.list_set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(list_set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(list_set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_LIST_SET_HPP
