// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_MAP_SET_HPP
#define DJINNI_GENERATED_PARCELABLE_MAP_SET_HPP

#include <iostream>
#include <string>
#include <unordered_map>
#include <unordered_set>
#include <utility>

namespace testsuite {

struct ParcelableMapSet final {
    std::unordered_map<std::string, std::unordered_set<std::string>> map_set;

    ParcelableMapSet(std::unordered_map<std::string, std::unordered_set<std::string>> map_set_)
    : map_set(std::move(map_set_))
    {}

    ParcelableMapSet(const ParcelableMapSet& cpy) {
       this->map_set = cpy.map_set;
    }

    ParcelableMapSet() = default;


    ParcelableMapSet& operator=(const ParcelableMapSet& cpy) {
       this->map_set = cpy.map_set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(map_set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(map_set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_MAP_SET_HPP
