// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_MAP_LIST_HPP
#define DJINNI_GENERATED_PARCELABLE_MAP_LIST_HPP

#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableMapList final {
    std::unordered_map<std::string, std::vector<std::string>> map_set;

    ParcelableMapList(std::unordered_map<std::string, std::vector<std::string>> map_set_)
    : map_set(std::move(map_set_))
    {}

    ParcelableMapList(const ParcelableMapList& cpy) {
       this->map_set = cpy.map_set;
    }

    ParcelableMapList() = default;


    ParcelableMapList& operator=(const ParcelableMapList& cpy) {
       this->map_set = cpy.map_set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(map_set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(map_set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_MAP_LIST_HPP
