// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_SET_HPP
#define DJINNI_GENERATED_PARCELABLE_SET_HPP

#include <iostream>
#include <string>
#include <unordered_set>
#include <utility>

namespace testsuite {

struct ParcelableSet final {
    std::unordered_set<std::string> set;

    ParcelableSet(std::unordered_set<std::string> set_)
    : set(std::move(set_))
    {}

    ParcelableSet(const ParcelableSet& cpy) {
       this->set = cpy.set;
    }

    ParcelableSet() = default;


    ParcelableSet& operator=(const ParcelableSet& cpy) {
       this->set = cpy.set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_SET_HPP
