// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_LIST_HPP
#define DJINNI_GENERATED_PARCELABLE_LIST_HPP

#include <iostream>
#include <string>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableList final {
    std::vector<std::string> l;

    ParcelableList(std::vector<std::string> l_)
    : l(std::move(l_))
    {}

    ParcelableList(const ParcelableList& cpy) {
       this->l = cpy.l;
    }

    ParcelableList() = default;


    ParcelableList& operator=(const ParcelableList& cpy) {
       this->l = cpy.l;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(l);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(l);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_LIST_HPP
