// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_MAP_HPP
#define DJINNI_GENERATED_PARCELABLE_MAP_HPP

#include <iostream>
#include <string>
#include <unordered_map>
#include <utility>

namespace testsuite {

struct ParcelableMap final {
    std::unordered_map<std::string, std::string> m;

    ParcelableMap(std::unordered_map<std::string, std::string> m_)
    : m(std::move(m_))
    {}

    ParcelableMap(const ParcelableMap& cpy) {
       this->m = cpy.m;
    }

    ParcelableMap() = default;


    ParcelableMap& operator=(const ParcelableMap& cpy) {
       this->m = cpy.m;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(m);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(m);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_MAP_HPP
