// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from parcelable.djinni

#ifndef DJINNI_GENERATED_PARCELABLE_OPTIONAL_LIST_HPP
#define DJINNI_GENERATED_PARCELABLE_OPTIONAL_LIST_HPP

#include "../../handwritten-src/cpp/optional.hpp"
#include <iostream>
#include <string>
#include <utility>
#include <vector>

namespace testsuite {

struct ParcelableOptionalList final {
    std::experimental::optional<std::vector<std::string>> optional_set;

    ParcelableOptionalList(std::experimental::optional<std::vector<std::string>> optional_set_)
    : optional_set(std::move(optional_set_))
    {}

    ParcelableOptionalList(const ParcelableOptionalList& cpy) {
       this->optional_set = cpy.optional_set;
    }

    ParcelableOptionalList() = default;


    ParcelableOptionalList& operator=(const ParcelableOptionalList& cpy) {
       this->optional_set = cpy.optional_set;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(optional_set);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(optional_set);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_PARCELABLE_OPTIONAL_LIST_HPP
