// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from enum_flags.djinni

#ifndef DJINNI_GENERATED_RECORD_WITH_FLAGS_HPP
#define DJINNI_GENERATED_RECORD_WITH_FLAGS_HPP

#include "access_flags.hpp"
#include <iostream>
#include <utility>

namespace testsuite {

struct RecordWithFlags final {
    access_flags access;

    RecordWithFlags(access_flags access_)
    : access(std::move(access_))
    {}

    RecordWithFlags(const RecordWithFlags& cpy) {
       this->access = cpy.access;
    }

    RecordWithFlags() = default;


    RecordWithFlags& operator=(const RecordWithFlags& cpy) {
       this->access = cpy.access;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(access);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(access);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_RECORD_WITH_FLAGS_HPP
