// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#ifndef DJINNI_GENERATED_RETURN_ONE_HPP
#define DJINNI_GENERATED_RETURN_ONE_HPP

#include <cstdint>
#include <memory>

namespace testsuite {

/** Used for C++ multiple inheritance tests */
class ReturnOne {
public:
    virtual ~ReturnOne() {}

    static std::shared_ptr<ReturnOne> get_instance();

    virtual int8_t return_one() = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_RETURN_ONE_HPP
