// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from test.djinni

#ifndef DJINNI_GENERATED_SAMPLE_INTERFACE_HPP
#define DJINNI_GENERATED_SAMPLE_INTERFACE_HPP

namespace testsuite {

/**
 * we need to test optional interface
 * this one will be used
 */
class SampleInterface {
public:
    virtual ~SampleInterface() {}
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_SAMPLE_INTERFACE_HPP
