// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from multiple_inheritance.djinni

#ifndef DJINNI_GENERATED_SECOND_LISTENER_HPP
#define DJINNI_GENERATED_SECOND_LISTENER_HPP

namespace testsuite {

/** Used for ObjC multiple inheritance tests */
class SecondListener {
public:
    virtual ~SecondListener() {}

    virtual void second() = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_SECOND_LISTENER_HPP
