// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from yaml-test.djinni

#ifndef DJINNI_GENERATED_TEST_OPTIONAL_EXTERN_INTERFACE_RECORD_HPP
#define DJINNI_GENERATED_TEST_OPTIONAL_EXTERN_INTERFACE_RECORD_HPP

#include "../../handwritten-src/cpp/optional.hpp"
#include "sample_interface.hpp"
#include <iostream>
#include <memory>
#include <utility>

struct TestOptionalExternInterfaceRecord final {
    std::shared_ptr<::testsuite::SampleInterface> sample_interface;

    TestOptionalExternInterfaceRecord(std::shared_ptr<::testsuite::SampleInterface> sample_interface_)
    : sample_interface(std::move(sample_interface_))
    {}

    TestOptionalExternInterfaceRecord(const TestOptionalExternInterfaceRecord& cpy) {
       this->sample_interface = cpy.sample_interface;
    }

    TestOptionalExternInterfaceRecord() = default;


    TestOptionalExternInterfaceRecord& operator=(const TestOptionalExternInterfaceRecord& cpy) {
       this->sample_interface = cpy.sample_interface;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(sample_interface);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(sample_interface);
    }
};
#endif //DJINNI_GENERATED_TEST_OPTIONAL_EXTERN_INTERFACE_RECORD_HPP
