// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from user_token.djinni

#ifndef DJINNI_GENERATED_USER_TOKEN_HPP
#define DJINNI_GENERATED_USER_TOKEN_HPP

#include <string>

namespace testsuite {

class UserToken {
public:
    virtual ~UserToken() {}

    virtual std::string whoami() = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_USER_TOKEN_HPP
