// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from single_language_interfaces.djinni

#ifndef DJINNI_GENERATED_USES_SINGLE_LANGUAGE_LISTENERS_HPP
#define DJINNI_GENERATED_USES_SINGLE_LANGUAGE_LISTENERS_HPP

#include <memory>

namespace testsuite {

class JavaOnlyListener;
class ObjcOnlyListener;

/**
 * Generating and compiling this makes sure other languages don't break
 * on references to interfaces they don't need.
 */
class UsesSingleLanguageListeners {
public:
    virtual ~UsesSingleLanguageListeners() {}

    virtual void callForObjC(const std::shared_ptr<ObjcOnlyListener> & l) = 0;

    virtual std::shared_ptr<ObjcOnlyListener> returnForObjC() = 0;

    virtual void callForJava(const std::shared_ptr<JavaOnlyListener> & l) = 0;

    virtual std::shared_ptr<JavaOnlyListener> returnForJava() = 0;
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_USES_SINGLE_LANGUAGE_LISTENERS_HPP
