// AUTOGENERATED FILE - DO NOT MODIFY!
// This file generated by Djinni from wchar_test.djinni

#ifndef DJINNI_GENERATED_WCHAR_TEST_REC_HPP
#define DJINNI_GENERATED_WCHAR_TEST_REC_HPP

#include <iostream>
#include <string>
#include <utility>

namespace testsuite {

struct WcharTestRec final {
    std::wstring s;

    WcharTestRec(std::wstring s_)
    : s(std::move(s_))
    {}

    WcharTestRec(const WcharTestRec& cpy) {
       this->s = cpy.s;
    }

    WcharTestRec() = default;


    WcharTestRec& operator=(const WcharTestRec& cpy) {
       this->s = cpy.s;
       return *this;
    }

    template <class Archive>
    void load(Archive& archive) {
        archive(s);
    }

    template <class Archive>
    void save(Archive& archive) const {
        archive(s);
    }
};

}  // namespace testsuite
#endif //DJINNI_GENERATED_WCHAR_TEST_REC_HPP
